import os
import json
import yfinance as yf
from google import genai
from fpdf import FPDF
from datetime import datetime

# 1. Initialize Gemini Client (Uses the API key stored in your GitHub secrets environment)
client = genai.Client()

# 2. Define your target tech and growth watchlist
tickers = ["MU", "NVDA", "ORCL", "SNDK", "MSFT", "VST", "TSM", "LLY", "LRCX", "NOW", "AMD", "CACI", "AVGO", "ANET"]
print("Fetching technical data from Yahoo Finance...")
data_summary = ""

for ticker in tickers:
    try:
        stock = yf.Ticker(ticker)
        # Fetching 1 month of price context to give accurate support/resistance evaluation
        hist = stock.history(period="1mo")
        if hist.empty:
            continue
        # Pull the last 10 sessions to feed to Gemini
        recent = hist.tail(10)
        data_summary += f"\n--- {ticker} Historical Data (Last 10 Sessions) ---\n"
        for index, row in recent.iterrows():
            date_str = index.strftime('%Y-%m-%d')
            data_summary += f"Date: {date_str} | Close: {row['Close']:.2f} | High: {row['High']:.2f} | Low: {row['Low']:.2f} | Vol: {int(row['Volume'])}\n"
    except Exception as e:
        print(f"Error gathering data for {ticker}: {e}")

# 3. Request a clean, structured JSON format from Gemini to feed directly into the PDF table
prompt = f"""
You are an expert institutional technical analyst. Based on the 10-day market price history provided below, analyze each individual stock. Find or compute the key near-term resistance level, key support level, current primary trend (e.g., Bullish, Bearish, Sideways), and provide a concise, professional "Important Note" explaining the key price action catalyst or breakout level.

Stocks to analyze: {', '.join(tickers)}

Data Input:
{data_summary}

CRITICAL INSTRUCTION: You must reply ONLY with a valid, clean JSON array of objects. Do not wrap it in ```json blocks, and do not include any extra text. 
Each object in the JSON array must follow this exact schema:
{{
  "stock_name": "TICKER",
  "resistance": "Resistance level value",
  "support": "Support level value",
  "trend": "Bullish/Bearish/Sideways",
  "important_note": "Technical commentary note here"
}}
"""

print("Generating structured technical analysis via Gemini API...")
# Calling the correct client method using the gemini-3.5-flash model identifier
response = client.models.generate_content(
    model='gemini-3.5-flash',
    contents=prompt,
)

# Clean up raw markdown block wrappers if generated by the model
raw_json = response.text.strip()
if raw_json.startswith("```"):
    lines = raw_json.splitlines()
    if lines[0].startswith("```"):
        lines = lines[1:]
    if lines[-1].startswith("```"):
        lines = lines[:-1]
    raw_json = "\n".join(lines).strip()

try:
    analysis_data = json.loads(raw_json)
except Exception as e:
    print("Failed to parse JSON. Falling back to an empty template table structure.")
    analysis_data = [{"stock_name": t, "resistance": "Error", "support": "Error", "trend": "Error", "important_note": "Failed to parse data."} for t in tickers]


# 4. Compile the Data into a Beautiful PDF Table Layout
class CorporatePDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(30, 41, 59) # Cool Slate 800
        self.cell(0, 10, "Daily Market Report - Watchlist Technical Summary", new_x="LMARGIN", new_y="NEXT", align="L")
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(100, 116, 139) # Slate 500
        self.cell(0, 5, f"Generated automatically on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", new_x="LMARGIN", new_y="NEXT", align="L")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(148, 163, 184) # Slate 400
        self.cell(0, 10, f"Page {self.page_no()}", align="C")

pdf = CorporatePDF()
pdf.add_page()

# Setup Table Columns matching your exact 5 columns
# Total printable width is roughly 190mm on standard A4 layout.
# Width configuration: stock_name(20), resistance(25), support(25), trend(25), important_note(95)
with pdf.table(col_widths=(20, 25, 25, 25, 95), text_align="LEFT") as table:
    # Render the Table Header row
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(15, 23, 42) # Slate 900
    header_row = table.row()
    headers = ["Stock Name", "Resistance", "Support", "Trend", "Important Note"]
    for header_title in headers:
        header_row.cell(header_title)

    # Render Data Rows dynamically
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(51, 65, 85) # Slate 700
    
for stock in analysis_data:
        row = table.row()
        
        # 1. Grab the trend value and normalize it for matching
        trend_status = str(stock.get("trend", "")).strip().lower()
        
        # 2. Assign text color dynamically based on the trend
        if "bullish" in trend_status:
            row_color = (34, 197, 94)   # Vibrant Green (RGB)
        elif "bearish" in trend_status:
            row_color = (239, 68, 68)   # Vibrant Red (RGB)
        else:
            row_color = (51, 65, 85)    # Default Slate 700 (RGB) for Sideways/Errors
            
        # 3. Apply the dynamic color directly to each cell in the row
        row.cell(str(stock.get("stock_name", "")), text_color=row_color)
        row.cell(str(stock.get("resistance", "")), text_color=row_color)
        row.cell(str(stock.get("support", "")), text_color=row_color)
        row.cell(str(stock.get("trend", "")), text_color=row_color)
        row.cell(str(stock.get("important_note", "")), text_color=row_color)
    
# Finalize the compiled PDF file
filename = "morning_market_analysis.pdf"
pdf.output(filename)
print(f"PDF output finalized successfully as {filename}.")
